### ISSUE TITLE
Server not downloading 

### ISSUE THREAD

**Issue by niloofaryousefi** [chathika/Py2NetLogo-Forked#1]
When typing `import nl4py`, it fails to download the server.jar files.

**Comment by chathika** [comment]
This seems to be a certificate issue when downloading the server jar files. I will make fix to handle the certificates as a next minor revision.

**Comment by chathika** [comment]
This bug has been addressed in [v0.2.0](https://github.com/chathika/NL4Py/releases/tag/v0.2.0)
